### ISSUE TITLE
Userstream (follow specific users)

### ISSUE THREAD

**Issue by warmspringwinds** [logstash-plugins/logstash-input-twitter#11]
Hello,

I have been using twitter river plugin for elasticsearch to collect tweets from a particular user.
Now I see that rivers are deprecated in the elasticsearch and that they recommend to use logstash for this purposes.

But I can't find a way to use your plugin for userstream.
Is it possible?

Thank you.

**Comment by futurechan** [comment]
:+1: I have the same need.

**Comment by tylerjl** [comment]
Seeing same problems here - adding any keywords prefixed with `@` causes the plugin to explode in a most spectacular fashion. Tested on logstash 1.5.0.rc2:

```json
{:exception=>Twitter::Error::Unauthorized, :backtrace=>["/Users/tylerjl/Work/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'", "org/ruby_http_parser/RubyHttpParser.java:370:in `<<'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/twitter/streaming/response.rb:16:in `<<'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/twitter/streaming/connection.rb:22:in `stream'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/twitter/streaming/client.rb:116:in `request'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/twitter/streaming/client.rb:36:in `filter'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-0.1.5/lib/logstash/inputs/twitter.rb:88:in `run'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:174:in `inputworker'", "/Users/tylerjl/Work/logstash-1.5.0.rc2/lib/logstash/pipeline.rb:168:in `start_input'"], :level=>:warn}
```

**Comment by dan-lind** [comment]
Same here:
{:status_code=>401, :header=>{"cache-control"=>"must-revalidate,no-cache,no-store", "connection"=>"close", "content-length"=>"289", "content-type"=>"text/html", "date"=>"Mon, 27 Apr 2015 19:23:44 GMT", "server"=>"tsa", "www-authenticate"=>"OAuth realm=\"Firehose\"", "x-connection-hash"=>"..."}}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Twitter consumer_key=>"...", keywords=>["@expert"], oauth_token=>"...">
  Error: End of file reached {:level=>:error}

**Comment by jordansissel** [comment]
I think there's a patch somewhere adding following user streams

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-input-twitter/pull/12 adds location and follow (follow == a user's mentions/stream/etc to follow)

**Comment by dan-lind** [comment]
Found it, but it seems to require 1.5.0. Tried that as well, but after downloading the logstash-input-twitter via the new plugin management system, I don't know how to patch it as I'm unable to find the actual twitter.rb file. Was expecting it to be under lib/logstash/inputs/ as before, but it's not there.

**Comment by guptayuvraj** [comment]
@tylerjl Did you find any solution? I am facing the same problem as you were facing.

**Comment by tylerjl** [comment]
@guptayuvraj not yet, unfortunately.

**Comment by purbon** [comment]
Released to #25

**Comment by purbon** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-twitter/pull/30

**Comment by Lbr1** [comment]
Good afternoon,

I recently started learning ELK, and I'm doing searches on twitter. As I was not able to search for user, I did a search and found your work "logstash-plugins / logstash-input-twitter", but since I am a newbie, I can not install the same.

1 - To begin with, I downloaded the .ZIP and extract its contents to the logstash-5.4.0 folder with the same name, logstash-input-twitter-master.

2 - Next in the same directory, I changed the gemfile file by adding the following line "gem" logstash-input-twitter-master ",: path =>" ./logstash-input-twitter-master ""

3- I logged into the logstash-5.4.0 / bin directory and executed the following command logstash-plugin install --no-verify and got the following error that I send in the image.

[http://imgur.com/a/kUdJM](url)
Could you help me? Thank you for your work, Regards

**Comment by Lbr1** [comment]
Sorry, I found my mistake there ""gem" logstash-input-twitter-**master** ", but now a get a " GemfileError: duplicate gem logstash-input-twitter" http://imgur.com/a/Tm0dX

Is that ok?

cmps
