### ISSUE TITLE
Logstash 1.5.1 Twitter Input Connection Refused

### ISSUE THREAD

**Issue by zWang95** [logstash-plugins/logstash-input-twitter#17]
Hi,

Getting connection refused error when trying to use Twitter input on Logstash 1.5.1.
I would appreciate any help. Thanks.

```
input {
    twitter {
        consumer_key => " "
        consumer_secret => " "
        oauth_token => " "
        oauth_token_secret => " "
        keywords => ["test"]
    }
}

output {
    stdout {}
}
```

bin/logstash agent -f logstash-twitter.conf

> io/console not supported; tty will not be manipulated
> Logstash startup completed
> ←[33mConnection refused - Connection refused {:exception=>#<Errno::ECONNREFUSED: Connection refused - Connection refused
> , :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'", "org/jruby/RubyIO.java:853:in`new'", "C:
> /Users/Michael_Wang3/Documents/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/twitter/streaming/connecti
> on.rb:16:in `stream'", "C:/Users/Michael_Wang3/Documents/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/twitter-5.12.0/lib/
> twitter/streaming/client.rb:116:in`request'", "C:/Users/Michael_Wang3/Documents/logstash-1.5.1/vendor/bundle/jruby/1.9/
> gems/twitter-5.12.0/lib/twitter/streaming/client.rb:36:in `filter'", "C:/Users/Michael_Wang3/Documents/logstash-1.5.1/ve
> ndor/bundle/jruby/1.9/gems/logstash-input-twitter-0.1.6/lib/logstash/inputs/twitter.rb:88:in`run'", "C:/Users/Michael_W
> ang3/Documents/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/pipeline.rb:176:in `inp
> utworker'", "C:/Users/Michael_Wang3/Documents/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/l
> ogstash/pipeline.rb:170:in`start_input'"], :level=>:warn}←[0m

**Comment by tarun005** [comment]
Been a while since you have posted this, did you solve this problem anyway? I am facing the same issue now. Has it got to do something with proxy?

**Comment by kares** [comment]
closing, this seems outdated - using plugin version 0.1.6
