### ISSUE TITLE
Docs not clear around Keywords field

### ISSUE THREAD

**Issue by skearns64** [logstash-plugins/logstash-input-twitter#18]
The docs for the Keyword field could be more helpful. 

I suggest three areas of improvement

 1. Setting `keywords => "*"` is not supported, and results in an Unauthorized exception, even though the actual issue is that a wildcard is not supported. 
 2. The syntax of the keywords field is not clear. It accepts multiple exact strings like `keywords => ["logstash", "example", "docs"] `
3. When entering multiple strings, there is an implied OR between them. This does not appear configurable.

**Comment by jasonrhaas** [comment]
@skearns64 I believe this is in line with how the Twitter Public API works.

https://dev.twitter.com/streaming/overview/request-parameters#track

Commas act as OR, spaces act as AND.

**Comment by purbon** [comment]
Fixed by @acchen97 in https://github.com/logstash-plugins/logstash-input-twitter/commit/38f6606d9a67ff6ff670513ddf814c906bb21dda please let us know what do you think? if happy, please go ahead and close the issue :+1:

**Comment by skearns64** [comment]
++ this is a big improvement!
