### ISSUE TITLE
Filter by hashtag, user, location, language

### ISSUE THREAD

**Issue by skearns64** [logstash-plugins/logstash-input-twitter#20]
The twitter river allowed filtering by hashtag, users, location, and language. We should support those here too. Simple keyword filtering is powerful, but lacks the richness of the additional filter options.

From the River docs:

> Filtered stream can also be supported (as per the twitter stream API). Filter stream can be configured to support tracks, follow, locations and language. user_lists is a shortcut to follow all members of a public twitter list identified by the user id and the list slug (last part of uri when open a list in your browser). The configuration is the same as the twitter API (a single comma separated string value, or using json arrays). Here is an example:

>```
PUT _river/my_twitter_river/_meta
{
    "type" : "twitter",
    "twitter" : {
        "filter" : {
            "tracks" : "test,something,please",
            "follow" : "111,222,333",
            "user_lists" : "ownerScreenName1/slug1,ownerScreenName2/slug2",
            "locations" : "-122.75,36.8,-121.75,37.8,-74,40,-73,41",
            "language" : "fr,en"
        }
    }
}
```

> Note that locations use geoJSON order (longitude, latitude).

> Note that if you want to use language filtering you need also to define at least one of tracks, follow or locations filter. Supported languages identifiers are BCP 47. You can filter whatever language defined in Twitter Advanced Search.

> Here is an array based configuration example:

>```
PUT _river/my_twitter_river/_meta
{
    "type" : "twitter",
    "twitter" : {
        "filter" : {
            "tracks" : ["test", "something"],
            "follow" : [111, 222, 333],
            "locations" : [ [-122.75,36.8], [-121.75,37.8], [-74,40], [-73,41]],
            "language" : [ "fr", "en" ]
        }
    }
}
```

**Comment by purbon** [comment]
@skearns64 to my knowledge, in the stream api there is no filter for hashtags, that for example is in the search api. i don't think we can implement this filter. Although the others will be easy implemented.

**Comment by purbon** [comment]
related to #11

**Comment by skearns64** [comment]
@purbon - [why] do we only use the streaming API? It seems like the search API is more powerful, no?

If we do use only the streaming API, it would be good to mention that in the docs, and include a note (or better - matching, documented API attributes) for the things that the streaming API does support.

**Comment by jordansissel** [comment]
@skearns64 In my experience, the search API is very limited and Twitter tends to be very heavy on the banhammer for searches by scripts. IIRC the searchability of the search api vs stream api is the same, but stream gets you after-now tweets where search gets you before-now tweets.

**Comment by purbon** [comment]
@skearns64 I think It makes sense to use the stream api, what people expect is tweets from now to the feature, not searching over the current set of tweets. What would be the benefits of using search? I don't really see much as of now.

One problem of using search is how do we discard events in the past, or already ingested? we should have to have a list of them somehow and this might be very complicated. what do you think?

**Comment by skearns64** [comment]
@purbon - right you are :) Streaming ftw!

**Comment by purbon** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-twitter/pull/30
