### ISSUE TITLE
Add sample endpoint (Option to pull from the firehose)

### ISSUE THREAD

**Issue by skearns64** [logstash-plugins/logstash-input-twitter#21]
For testing purposes, pulling from the firehose would be a useful way to feed data. Perhaps the firehose could be automatically selected if the Keyword was omitted.

**Comment by purbon** [comment]
@skearns64 I do really would like to implement this feature to easy testing, it would be nice if you could provide some context to your requests:

* What do you mean with firehose? can you elaborate this a bit more?
* Which kind of testing are you thinking? something like pulling data in a real env? 

Looking forward to know more about it.

- purbon

**Comment by purbon** [comment]
@skearns64 after doing some research at the twitter api, I got that firehouse is.

**Comment by skearns64** [comment]
@purbon - I said firehose, but I didn't mean it :) Very few people have access to read from the actual firehose, I believe it's quite expensive. 

There are other ways to get a sampling of data: https://dev.twitter.com/streaming/reference/get/statuses/sample


And by "testing" I meant, "making sure the logstash input is working, with a minimum amount of configuration". Today, I believe that if you don't put in filter terms, it doesn't grab anything, which I found mildly confusing.

**Comment by purbon** [comment]
Thanks for your feedback @skearns64, I will be extending the test suites of this plugin. I will be thinking how to add this feature in a nice way when the user have all setup in a real life scenario.

**Comment by purbon** [comment]
related to #6

**Comment by dadoonet** [comment]
+1 :)

**Comment by purbon** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-twitter/pull/30
