### ISSUE TITLE
Problem with twitter-plugin and https-proxies Logstash

### ISSUE THREAD

**Issue by kodo651** [logstash-plugins/logstash-input-twitter#41]
Sorry for bothering you here but the elasticsearch forum is _dead_ at least my question has been left untouched for several weeks now - maybe my questions is stupid...:)

---

I have logstash v2.3.2 installed and wanted to try the twitter-plugin again after abandoning it earlier in favor for a custom developed twitterstream-client.

Setting the proxy-relevant settings to:

use_proxy => true
proxy_address => "xxx.yyy.zzz"
proxy_port => xxxx

I get loads of the following exceptions when logstash starts:

{:timestamp=>"2016-05-19T13:13:08.304000+0200", :message=>"End of file reached", :exception=>#, :backtrace=>["org/jruby/RubyIO.java:2895:in readpartial'", "E:/twitter/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter/patches.rb:30:instream'", "E:/twitter/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter/patches.rb:58:in request'", "E:/twitter/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:infilter'", "E:/twitter/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.2/lib/logstash/inputs/twitter.rb:128:in run'", "E:/twitter/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:342:ininputworker'", "E:/twitter/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:336:in `start_input'"], :options=>nil, :level=>:warn}

Now, if I set use_proxy => false logstash starts but of course I get a connection refused error as the twitter-plugin is unable to connect to my proxy which uses https. I guess the plugin defaults to http.

Is this a known problem and is there a workaround?

**Comment by rahullao** [comment]
Hi,

I am facing the same issues.

Please can you update the progress on this issue.
