### ISSUE TITLE
logstash-twitter input issu with proxy 

### ISSUE THREAD

**Issue by DBARUNNER** [logstash-plugins/logstash-input-twitter#47]
Hello i am using logstash 5.2.1 latest version when i run the twiiter-input plugin without the proxy it work fine but it doesnt work with proxy and give me connection refused error 
any one could help me ?

sorry for question here elastic.discus doesn't answear me

**Comment by kares** [comment]
we recently double checked [proxy](https://github.com/logstash-plugins/logstash-input-twitter/pull/69) support, and also given this is an old report I am closing the issue.
