### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by dadoonet** [logstash-plugins/logstash-input-twitter#7]
Twitter river supports proxy setting. See https://github.com/elasticsearch/elasticsearch-river-twitter#using-a-proxy

Would be nice to have it in Twitter Input as well.

**Comment by suyograo** [comment]
Also reported here https://github.com/elasticsearch/logstash/issues/1743

**Comment by suyograo** [comment]
From @schmorgs

Hi,
I'm trying to get the logstash Twitter v1.4.2 input working through a proxy server (on both Linux and Windows), but having no luck.
The same configuration works without a proxy, but I get the error with a proxy ::

A plugin had an unrecoverable error. Will restart this plugin.
Plugin: <LogStash::Inputs::Twitter consumer_key=>"xxxxx, oauth_token=>"xxxx", keywords=>["bitcoin", "scotland"], type=>"twitter">
Error: Connection refused - Connection refused {:level=>:error}
Config looks something like this :

input {
  twitter {
    consumer_key => "xxxx"
    consumer_secret => "xxxx"
    oauth_token => "xxxx"
    oauth_token_secret => "xxxx"
    keywords => ["bitcoin","scotland"]
    type => "twitter"
    full_tweet => true
  }
}
filter {
}
output {
  stdout {}
}
It looks like the Twitter input used to support proxy but it was removed. Any plans to bring it back or any knows workaround I can try?

**Comment by DavidNorman** [comment]
Hi.

Any movement on this?

**Comment by DavidNorman** [comment]
https://github.com/sferik/twitter/blob/master/examples/Configuration.md

**Comment by kodo651** [comment]
I'm also very interested to know if there's any solution to this in the foreseeable future? I guess alot of users are behind a firewall...

**Comment by matttharma** [comment]
Any progress on this guys? I am also stuck behind a proxy!!

**Comment by purbon** [comment]
working on getting this functionality in, got most of it working. writing test now before publishing a PR for this.

**Comment by purbon** [comment]
Got this fixed and working in #29, see the PR for last implementation and testing details.

**Comment by kodo651** [comment]
Really appreciate the efforts you put into this! It looks very promising but I'm still unable to retrieve tweets using the updated plugin. The errors I receive looks like this:

←[33mundefined method `filter' for nil:NilClass {:exception=>#<NoMethodError: un
defined method `filter' for nil:NilClass>, :backtrace=>["e:/twitter/ls/vendor/bu
ndle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:
128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-j
ava/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle
/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_
input'"], :options=>nil, :level=>:warn}←[0m

The settings I've added to my logstash-config looks like this:

		use_proxy => 'true'
		proxy_address => <our proxy host>'
		proxy_port => <our proxy port

We use the same proxy-configuration för http, https and ftp.

What am I doing wrong here...?

**Comment by purbon** [comment]
@kodo651 your error looks strange to me because it looks like your  ```stream_client``` never got initialized, can you run your logstash process with ```--debug```? this might provide with more logging.

**Comment by purbon** [comment]
@kodo651 I have an strong feeling that this might be related with the plugin not able to recover if something wrong happen, see https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipeline.rb#L202-L234 for more details. Your debug log will help track this down, thanks a lot.

**Comment by kodo651** [comment]
Ok... this is the output with the debug switch on (some of the authorization and keyword stuff removed):

{:timestamp=>"2015-12-01T11:14:50.164000+0100", :message=>"Compiled pipeline code:\n        @inputs = []\n        @filters = []\n        @outputs = []\n        @periodic_flushers = []\n        @shutdown_flushers = []\n\n          @input_twitter_1 = plugin(\"input\", \"twitter\", LogStash::Util.hash_merge_many({ \"consumer_key\" => (\"...\") }, { \"consumer_secret\" => (\"...\") }, { \"oauth_token\" => (\"...\") }, { \"oauth_token_secret\" => (\"...\") }, { \"keywords\" => [(\"...\")] }, { \"use_proxy\" => (\"true\") }, { \"proxy_address\" => (\"...\") }, { \"proxy_port\" => ... }))\n\n          @inputs << @input_twitter_1\n\n          @output_stdout_2 = plugin(\"output\", \"stdout\")\n\n          @outputs << @output_stdout_2\n\n  def filter_func(event)\n    events = [event]\n    @logger.debug? && @logger.debug(\"filter received\", :event => event.to_hash)\n    events\n  end\n  def output_func(event)\n    @logger.debug? && @logger.debug(\"output received\", :event => event.to_hash)\n    @output_stdout_2.handle(event)\n    \n  end", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb", :line=>"38", :method=>"initialize"}
{:timestamp=>"2015-12-01T11:14:50.164000+0100", :message=>"Plugin not defined in namespace, checking for plugin file", :type=>"input", :name=>"twitter", :path=>"logstash/inputs/twitter", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/plugin.rb", :line=>"76", :method=>"lookup"}
{:timestamp=>"2015-12-01T11:14:50.476000+0100", :message=>"Plugin not defined in namespace, checking for plugin file", :type=>"codec", :name=>"plain", :path=>"logstash/codecs/plain", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/plugin.rb", :line=>"76", :method=>"lookup"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Codecs::Plain/@charset = \"UTF-8\"", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@consumer_key = \"...\"", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@consumer_secret = <password>", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@oauth_token = \"...\"", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@oauth_token_secret = <password>", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@keywords = [\"...\"]", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@use_proxy = true", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@proxy_address = \"...\"", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@proxy_port = ...", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.492000+0100", :message=>"config LogStash::Inputs::Twitter/@codec = <LogStash::Codecs::Plain charset=>\"UTF-8\">", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.508000+0100", :message=>"config LogStash::Inputs::Twitter/@add_field = {}", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.508000+0100", :message=>"config LogStash::Inputs::Twitter/@full_tweet = false", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.508000+0100", :message=>"config LogStash::Inputs::Twitter/@use_samples = false", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.508000+0100", :message=>"config LogStash::Inputs::Twitter/@ignore_retweets = false", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.508000+0100", :message=>"Plugin not defined in namespace, checking for plugin file", :type=>"output", :name=>"stdout", :path=>"logstash/outputs/stdout", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/plugin.rb", :line=>"76", :method=>"lookup"}
{:timestamp=>"2015-12-01T11:14:50.523000+0100", :message=>"Plugin not defined in namespace, checking for plugin file", :type=>"codec", :name=>"line", :path=>"logstash/codecs/line", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/plugin.rb", :line=>"76", :method=>"lookup"}
{:timestamp=>"2015-12-01T11:14:50.523000+0100", :message=>"config LogStash::Codecs::Line/@charset = \"UTF-8\"", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.523000+0100", :message=>"config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::Line charset=>\"UTF-8\">", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.539000+0100", :message=>"config LogStash::Outputs::Stdout/@workers = 1", :level=>:debug, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/config/mixin.rb", :line=>"122", :method=>"config_init"}
{:timestamp=>"2015-12-01T11:14:50.944000+0100", :message=>"Pipeline started", :level=>:info, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb", :line=>"108", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:50.976000+0100", :message=>"Starting twitter tracking", :track=>"...", :level=>:info, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"120", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.147000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.178000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.210000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.241000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.256000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.288000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}
{:timestamp=>"2015-12-01T11:14:51.303000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:in `readpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in `stream'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb:128:in `run'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:205:in `inputworker'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in `start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"}


...and the last line is "repeated forever"...

**Comment by purbon** [comment]
@kodo651 from

```
"e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/pipeline.rb:198:in start_input'"], :options=>nil, :level=>:warn, :file=>"/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter.rb", :line=>"138", :method=>"run"} {:timestamp=>"2015-12-01T11:14:51.288000+0100", :message=>"End of file reached", :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:2895:inreadpartial'", "e:/twitter/ls/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-2.2.0/lib/logstash/inputs/twitter/patches.rb:30:in stream'", 
```

I see https://github.com/logstash-plugins/logstash-input-twitter/blob/master/lib/logstash/inputs/twitter/patches.rb#L30 is having problem to connect to your proxy. 

BTW, I can not see the the issue described https://github.com/logstash-plugins/logstash-input-twitter/issues/7#issuecomment-160921799 in your last stack trace, does it makes sense to you?

Thanks a lot for your issue.

**Comment by kodo651** [comment]
I'm so sorry - I forgot to mention I did an plugin-uninstall of the twitter-plugin existing in the logstash 2.1.0 version and then did a manual plugin install of the new twitter-input-plugin. That solved the problem with the plugin not knowing about the proxy-related settings. Now when I start the plugin I get the errors described above. Sorry for any confusion this may have caused you...

**Comment by purbon** [comment]
No problem! oh, I forgot about it, sorry, yeah to work with proxy you need the last version. In your case I would investigate the connection with the proxy? is your proxy requiring authentication?

**Comment by kodo651** [comment]
Hmmmm, that is a tricky question - there might be a need for authentication... I thought that it would use my ad-account which I use when login on the win-domain BUT at the same time I understand we're talking about stuff here which might not honor the "windows proxy" interaction. Is it possible to specify credentials either by providing them as settings OR provide them using environment variables?

**Comment by kodo651** [comment]
FYI I already have JAVA_OPTS set to -Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port>

and the same goes for https...

**Comment by purbon** [comment]
Hi

On Tue, 1 Dec 2015 13:02 kodo651 <notifications@github.com> wrote:

Hmmmm, that is a tricky question - there might be a need for
authentication... I thought that it would use my ad-account which I use
when login on the win-domain BUT at the same time I understand we're
talking about stuff here which might not honor the "windows proxy"
interaction. Is it possible to specify credentials either by providing them
as settings OR provide them using environment variables?

This is not possible as of today, will add an issue and work on it. I will
let you know.

/purbon

—
Reply to this email directly or view it on
<https://github.com/logstash-plugins/logstash-input-twitter/issues/7#issuecomment-160947177>
GitHub
<https://github.com/logstash-plugins/logstash-input-twitter/issues/7#issuecomment-160947177>.<img
src="
https://ci5.googleusercontent.com/proxy/KgHDsxWKfnAGEC3RoJtI8Jet5GBLdfT0tdknEmF9Rn9rDKnINHUI6mW4y-7EbjyNDg9zplEHHYOLsDmpS9KuAHN4Mo-_wYHQSpGRPLNG1nBZ1AH_Cs6gHh3y8Vp-NIwvHEH6GurCZjj3tkFJDSReW11K2fUxZg=s0-d-e1-ft#https://github.com/notifications/beacon/AAELvFS1xDNNs65fEYE5mlrcRz8jinf-ks5pLYPTgaJpZM4DZc2G.gif
">

**Comment by purbon** [comment]
This will not work because of the way the twitter lib does proxy. Will
provide more details soon.

On Tue, 1 Dec 2015 13:07 kodo651 <notifications@github.com> wrote:

FYI I already have JAVA_OPTS set to -Dhttp.proxyHost= -Dhttp.proxyPort=

and the same goes for https...


—
Reply to this email directly or view it on
<https://github.com/logstash-plugins/logstash-input-twitter/issues/7#issuecomment-160948848>
GitHub
<https://github.com/logstash-plugins/logstash-input-twitter/issues/7#issuecomment-160948848>.<img
src="
https://ci3.googleusercontent.com/proxy/x_uJ3RCcHgCxFDwIOENDmQ3e085ouenci6dpxVQvqcfqsbzXhD2DYh39ejoD4bWXqse0WXb05EHnuw3tHlKW_FtP6KvRhykov9yYsfvKOPKJgHsm2QUIPOuPQV2L06sCfQt0dxYpJKBKdjzx1Q8FUMiHHrVaUQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAELvGGQMOqxp7b-9_mQyqY81mBwvVZOks5pLYTzgaJpZM4DZc2G.gif
">

**Comment by kodo651** [comment]
Ok thanks for your efforts on this! Do you have a rough estimate when you think this may be available? Depending on your reply I will need to make a decision if I should go with one of my other solution based on Java-services and RabbitMQ. A bit overkill for my use case here so going with a light stack of logstash, es and Kibana is the preferred way to go...

**Comment by purbon** [comment]
@kodo651 see #32 for updates.
