### ISSUE TITLE
Add ignore_retweets flag

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-input-twitter#9]
There is a flag if an item is a retweet.  If true, prevent an event from getting queued.

**Comment by jordansissel** [comment]
Can this compare to `if [retweeted] { drop { } }` ?

**Comment by untergeek** [comment]
Totally!  @suyograo and I had this discussion already.  We considered leaving it as a conditional + filter option, or catching the flag in the event and dropping it in the input.  Because the twitter river does the latter (use a flag), @suyograo opted to go the flag route.  I'm fine either way, though.

Thoughts?

**Comment by jordansissel** [comment]
hmm... On one hand, feature parity with the twitter river could be nice for deprecating that, but on the other hand rivers have no filtering facilities so it *had* to have a flag for that.

My preference is to document how to drop retweets, not expose a special setting. If we document it, the feature-parity is there for the river and input plugin, but with no extra code.

**Comment by jordansissel** [comment]
However, my general opinion is that such a small setting doesn't matter in the long term, but I framing it in terms of all plugins - If the answer to "Can we do this in a filter?" is "Yes" then I don't think it really belongs in an input setting.

**Comment by suyograo** [comment]
re: documenting vs config (and doing this behind the scenes), I was thinking more in the line of making it easy for users coming from ES river to LS twitter input.

**Comment by purbon** [comment]
I think both ideas are good, but not sure if for a such small "filtering" option we should make users write a concrete filter statement, events could be already dropped in the input and not enter the pipeline. I imagine this as if provided by the twitter api, or gem, we will be leveraging this probably in the input, right?

**Comment by purbon** [comment]
Added this flag in https://github.com/logstash-plugins/logstash-input-twitter/pull/30, will close this issue for now.
